import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styled, { css } from "styled-components";
import Map from "../components/map";
import Select from "react-select";
import { useQuery } from "react-query";
import { stateSalesService } from "../services/stateSales.service";
import { Range } from "../types";

const rangeOptions = [
  { value: { low: 0, high: 250 }, label: "0 - 250" },
  { value: { low: 250, high: 500 }, label: "250 - 500" },
  { value: { low: 500, high: 1000 }, label: "500 - 1000" },
  { value: { low: 1000, high: Number.MAX_SAFE_INTEGER }, label: "1000+" },
];

const Header = styled.div`
  height: 95px;
  padding-left: 25px;
  box-shadow: 0 2px 5px lightgray;
`;

const Container = styled.div`
  margin-top: 88px;
  display: flex;
  align-items: center;
  flex-direction: column;
`;

const Content = styled.div`
  width: fit-content;
`;

const Controls = styled.div`
  margin: 0px;
  margin-bottom: 120px;
  scale: 2;
  width: fit-content;
  height: 20px;
  margin-left: 90px;
  font-size: 24px;
`;

const Text = styled.div`
  font-weight: bold;
  margin-bottom: 10px;
`;

const ErrorMsg = styled.div`
  margin-top: 10px;
  color: crimson;
  font-size: 12px;
`;

const Home: NextPage = () => {
  const [highlightedStates, setHighlightedStates] = useState<string[]>([]);
  const [selectedRange, setSelectedRange] = useState<Range>(
    rangeOptions[0].value
  );

  let { data, isLoading, isError } = useQuery(
    "stateSales",
    async () => await stateSalesService.get()
  );

  useEffect(() => {
    const stateIds: string[] = [];
    data?.forEach((state) => {
      if (
        state.visits >= selectedRange.low &&
        state.visits <= selectedRange.high &&
        !stateIds.includes(state.id.toLowerCase())
      )
        stateIds.push(state.id.toLowerCase());
    });
    setHighlightedStates(stateIds);
  }, [data, setHighlightedStates, selectedRange]);

  return (
    <div>
      <Head>
        <title>State Sales Map</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="map.ico" />
      </Head>
      <div>
        <Header>
          <Image
            src="/logo.svg"
            width={215}
            height={95}
            alt="Kiwi standing on oval"
          />
        </Header>
        <Container>
          <Content>
            <Controls>
              <Text>Users visits</Text>
              <Select
                styles={{
                  menu: (provided) => ({
                    ...provided,
                    marginTop: 1,
                  }),
                  container: (provided) => ({ ...provided, width: 188 }),
                  indicatorSeparator: (provided) => ({
                    ...provided,
                    visibility: "hidden",
                  }),
                }}
                isLoading={isLoading}
                options={rangeOptions}
                defaultValue={rangeOptions[0]}
                onChange={(newValue) => {
                  setSelectedRange(newValue?.value ?? rangeOptions[0].value);
                }}
              />
              {isError && (
                <ErrorMsg>
                  We&apos;re sorry, but we couldn&apos;t reach out data source
                </ErrorMsg>
              )}
            </Controls>
            <Map highlightedStates={highlightedStates}></Map>
          </Content>
        </Container>
      </div>
    </div>
  );
};

export default Home;
